{"uuid": "bb4c6159-14d7-4673-9055-f49c72218a7f", "children": ["8a6e4180-30d1-41b4-b0ee-f607ef735c03"], "befores": [{"name": "init_context", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestMetadata' object has no attribute 'context'\n", "trace": "  File \"C:\\tools\\Python\\Python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 180, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\tools\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 868, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\tools\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 750, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\ws\\pydemo\\case\\base.py\", line 25, in init_context\n    if self.__getattribute__('context') is not None:\n"}, "start": 1532500852319, "stop": 1532500852319}], "start": 1532500852319, "stop": 1532500852451}