{"name": "test_all_metadata", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestMetadata' object has no attribute 'context'", "trace": "self = <case.anly.test_metadata.TestMetadata object at 0x048936B0>\n\n    @pytest.fixture(scope='function', autouse=True)\n    def init_context(self):\n>       if self.__getattribute__('context') is not None:\nE       AttributeError: 'TestMetadata' object has no attribute 'context'\n\n..\\base.py:25: AttributeError"}, "uuid": "8a6e4180-30d1-41b4-b0ee-f607ef735c03", "historyId": "cbc10bea9d93e65c3ac4dadc1594995d", "fullName": "case.anly.test_metadata.TestMetadata#test_all_metadata", "labels": [{"name": "host", "value": "PVGN56588630A"}, {"name": "thread", "value": "20680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.anly.test_metadata"}]}