{"name": "test_all_metadata", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestMetadata' object has no attribute 'context'", "trace": "self = <case.anly.test_metadata.TestMetadata object at 0x04A4F670>\n\n    @pytest.fixture(scope='function', autouse=True)\n    def init_context(self):\n>       print('context', self.context)\nE       AttributeError: 'TestMetadata' object has no attribute 'context'\n\n..\\base.py:25: AttributeError"}, "uuid": "ccc80d60-340e-49b5-b18c-1dba909951aa", "historyId": "cbc10bea9d93e65c3ac4dadc1594995d", "fullName": "case.anly.test_metadata.TestMetadata#test_all_metadata", "labels": [{"name": "host", "value": "PVGN56588630A"}, {"name": "thread", "value": "9972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.anly.test_metadata"}]}