{"uuid": "22ed05ec-1c33-41e5-855f-d7d0b3050a99", "children": ["ccc80d60-340e-49b5-b18c-1dba909951aa"], "befores": [{"name": "init_context", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestMetadata' object has no attribute 'context'\n", "trace": "  File \"C:\\tools\\Python\\Python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 180, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\tools\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 868, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\tools\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 750, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\ws\\pydemo\\case\\base.py\", line 25, in init_context\n    print('context', self.context)\n"}, "start": 1532500744873, "stop": 1532500744873}], "start": 1532500744873, "stop": 1532500745081}